export const HORIZONTAL_CRITERIA_THRESHOLD = 100
export const MIN_X_BACKWARD_OFFSET = 250
export const MAX_X_BACKWARD_OFFSET = 500
export const MIN_Y_BACKWARD_OFFSET = 50
export const MAX_Y_BACKWARD_OFFSET = 80
export const Y_BACKWARD_OFFSET_DELIMITER = 3

export const X_FORWARD_OFFSET_DELIMITER = 2
export const X_FORWARD_OFFSET_THRESHOLD = 35
export const X_FORWARD_OFFSET_MINIMUM = 20
