name: e2e

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .pnpm-store
            ./packages/react-flow-editor/node_modules
            ./packages/e2e/node_modules
            ./packages/examples/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Download built assets
        uses: actions/download-artifact@v3
        with:
          name: react-flow-editor-dist
          path: packages/react-flow-editor/dist

      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: .cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Cypress
        run: CYPRESS_CACHE_FOLDER=./.cache/Cypress npx cypress install

      - name: Start server
        run: pnpm run serve:ci &
        env:
          CI: true

      - name: Run Cypress tests
        run: pnpm run cypress:ci
        env:
          CI: true
