name: lint

on:
  - pull_request

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.18.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build react-flow-editor
        run: pnpm --dir ./packages/react-flow-editor run build && pnpm i

      - name: Run prettier
        run: pnpm run prettier

      - name: Run eslint
        run: pnpm run eslint

      - name: Run typescript lint
        run: pnpm run typescript
